### ISSUE TITLE
Typo in Description

### ISSUE THREAD

**Issue by mynote** [JessYanCoding/RxErrorHandler#4]
There's a typo in the description (and it doesnt match the proper class name anyway).

ResponseErroListener must be **ResponseErrorListener** (missing r).

Regards, Emanuel

**Comment by JessYanCoding** [comment]
Thanks,fixed

**Comment by mynote** [comment]
Your welcome. Same issue in the commit description for .travis.yml.

**Comment by JessYanCoding** [comment]
Yes,i can see,but i can not modify it
