### ISSUE TITLE
使用errorHandler后subscribe 返回void 怎么返回Disposable

### ISSUE THREAD

**Issue by wushange** [JessYanCoding/RxErrorHandler#7]
使用errorHandler后subscribe 返回void 怎么返回Disposable 我想要管理Disposable

**Comment by wushange** [comment]
@Override
						public void onSubscribe(Disposable d) {
							super.onSubscribe(d);
							mDisposable.add(d);
						}

**Comment by JessYanCoding** [comment]
返回 void，和 RxErrorHandler 没有关系吧，这是 **Rxjava** 自己返回的，RxErrorHandler 也无能为力

**Comment by JessYanCoding** [comment]
嗯，就这样用
