### ISSUE TITLE
可以考虑增加对RxJavaPlugins.setErrorHandler的处理

### ISSUE THREAD

**Issue by hacket** [JessYanCoding/RxErrorHandler#8]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling
```
RxJavaPlugins.setErrorHandler(e -> {
    if (e instanceof UndeliverableException) {
        e = e.getCause();
    }
    if ((e instanceof IOException) || (e instanceof SocketException)) {
        // fine, irrelevant network problem or API that throws on cancellation
        return;
    }
    if (e instanceof InterruptedException) {
        // fine, some blocking code was interrupted by a dispose call
        return;
    }
    if ((e instanceof NullPointerException) || (e instanceof IllegalArgumentException)) {
        // that's likely a bug in the application
        Thread.currentThread()
                .getUncaughtExceptionHandler()
                .uncaughtException(Thread.currentThread(), e);
        return;
    }
    if (e instanceof IllegalStateException) {
        // that's a bug in RxJava or in a custom operator
        Thread.currentThread()
                .getUncaughtExceptionHandler()
                .uncaughtException(Thread.currentThread(), e);
        return;
    }
});
```

**Comment by JessYanCoding** [comment]
很久之前深度的使用过，有些需求不能实现

**Comment by hacket** [comment]
@JessYanCoding 能举例说明下什么需求实现不了？这是我增加对`RxJavaPlugins.setErrorHandler(e -> {})`的支持：
[add undeliverable error listener](https://github.com/hacket/RxErrorHandler/commit/36b6cda52860ed968d99fb261b31d653c010c4c5)

**Comment by JessYanCoding** [comment]
因为很久之前的事了，很多都忘了，记得当时花了一个上午，进行使用，依稀记得，大概是设置 RxJavaPlugins.setErrorHandler 后，只是传入 Consumer 是可以的，但是传入 Observer 会有问题，或者重写 onError 也会有问题，在一些情况下用户的操作，会导致 setErrorHandler 里传入的监听器不回调，大概记不清楚了，你可以自己多试试

**Comment by JessYanCoding** [comment]
另外，感谢你的提交，但是这里还需要提醒一点，如果 RxJavaPlugins.setErrorHandler 是可行的方案，那用户完全可以自行在 App  初始化时，自己调用该接口传入监听器，即可实现全局错误监听，无需通过 RxErrorHandler 再封装一层了，这样感觉有点多此一举，反而更复杂了，因为 RxJavaPlugins.setErrorHandler 使用已经足够简单了，不需要再多引入一个库

**Comment by hacket** [comment]
> 因为很久之前的事了，很多都忘了，记得当时花了一个上午，进行使用，依稀记得，大概是设置 RxJavaPlugins.setErrorHandler 后，只是传入 Consumer 是可以的，但是传入 Observer 会有问题，或者重写 onError 也会有问题，在一些情况下用户的操作，会导致 setErrorHandler 里传入的监听器不回调，大概记不清楚了，你可以自己多试试

嗯，我留意下这个问题。

**Comment by hacket** [comment]
> 另外，感谢你的提交，但是这里还需要提醒一点，如果 RxJavaPlugins.setErrorHandler 是可行的方案，那用户完全可以自行在 App 初始化时，自己调用该接口传入监听器，即可实现全局错误监听，无需通过 RxErrorHandler 再封装一层了，这样感觉有点多此一举，反而更复杂了，因为 RxJavaPlugins.setErrorHandler 使用已经足够简单了，不需要再多引入一个库

是可以单独用，既然封装了这个库，那就把rx异常相关的处理都统一到一个地方不是更好么？

**Comment by JessYanCoding** [comment]
我是认为，如果  RxJavaPlugins.setErrorHandler 足够完美，就不需要 RxErrorHandler，RxErrorHandler 的所有功能，RxJavaPlugins.setErrorHandler 这一个 API 即可实现
