### ISSUE TITLE
handleError传入自定义view

### ISSUE THREAD

**Issue by xilost** [JessYanCoding/RxErrorHandler#9]
因为大部分页面都需要加上错误的缺省页，能不能在handleError里传入一个自动view方便做全局处理？

**Comment by JessYanCoding** [comment]
View 和你当前的页面 (Activity, Fragment) 相关，这个框架是拿不到的哈，你可以参考 [MVPArms 中 AppManager 的方法](https://github.com/JessYanCoding/MVPArms/blob/master/arms/src/main/java/com/jess/arms/integration/AppManager.java#L232)，这个能满足你做全局处理的需求
